### ISSUE TITLE
Queue should use collection.observe to get available jobs without polling

### ISSUE THREAD

**Issue by mitar** [vsivsi/meteor-job#2]
Queue should use `collection.observe` to get available jobs without polling. Then latency between tasks added to the queue and it being executed would be minimized.

**Comment by vsivsi** [comment]
Closing this old issue.  I will look into providing some sample code in `meteor-job-collection` to show how to implement an `.observe()` based queuing mechanism.  Or perhap @mitar can point me to the code he has written to do this? :smile:

**Comment by mitar** [comment]
It is [here](https://github.com/peerlibrary/peerlibrary/blob/development/server/lib/worker.coffee#L121), but it requires implementation which throws an exception if a race-condition was detected, instead of returning an empty list then as well.

**Comment by vsivsi** [comment]
@mitar  Thanks, looks good. Before the 1.0 release, I'll to distill that into some sample code to show others how it can be done. -V

**Comment by mitar** [comment]
I could also implement it as a package, probably. Didn't yet have time for that. But first you decide on the API for me to detect a race-condition. You didn't like the exception throwing API.

**Comment by vsivsi** [comment]
@mitar, You are going to be very happy with the über simple solution I devised for this longstanding issue:

https://github.com/vsivsi/meteor-job-collection/tree/dev#qtrigger---anywhere
https://github.com/vsivsi/meteor-job/tree/dev#qtrigger

**Comment by mitar** [comment]
Cool! :-)

**Comment by mitar** [comment]
I think a better query to observe would be:

```
.find({status: 'ready', runId: null}, {sort: {priority: 1, retryUntil: 1, after: 1}, fields: {_id: 1}}).observe
```

**Comment by vsivsi** [comment]
Thanks for the input on the query.  `runId: null` is redundant because if the status is `"ready"` then `runId` must be `null`. The object state would be inconsistent otherwise. 

Sorting should make no difference to the observe, because the `find()` embedded within the `getWork()` call already handles all of the priority and age sorting each time work is requested: https://github.com/vsivsi/meteor-job-collection/blob/master/shared.coffee#L320

Reducing the `fields` to just the `_id` is reasonable, although for remote workers I'm not sure how much data on the wire it will save, because the local collection will be synced to the records produced by the query in the server `publish` function. So in that case, the publish function seems like the place to pare back the query that triggers the observe if cutting down of unnecessary bandwidth is the goal.

**Comment by mitar** [comment]
> runId: null is redundant because if the status is "ready" then runId must be null. The object state would be inconsistent otherwise. 

I copied the query from `getWork`. :-) You have the same [here](https://github.com/vsivsi/meteor-job-collection/blob/master/shared.coffee#L317). :-)

**Comment by mitar** [comment]
But yes, I agree. Maybe it is unreasonable, I just wanted to make it as similar to `getWork` query as possible.

**Comment by vsivsi** [comment]
True enough... That's just me being paranoid...  :smile:   

On the observe query, it probably doesn't matter much, but I wanted to keep it simple for the example code.

**Comment by mitar** [comment]
OK. No problem. I just wanted to make sure there is nothing missing. :-)
